{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Test Classifiers and GUI"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [],
   "source": [
    "import user_interface as ui\n",
    "import pickle as pk\n",
    "\n",
    "with open('dig_KNN_clf.pickle','rb') as f:\n",
    "    dig_KNN_clf = pk.load(f)\n",
    "with open('dig_MLP_clf.pickle','rb') as f:\n",
    "    dig_MLP_clf = pk.load(f)\n",
    "with open('let_MLP_clf.pickle', 'rb') as f:\n",
    "    let_MLP_clf = pk.load(f)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nelso\\Anaconda3\\envs\\ML_BHT\\lib\\tkinter\\__init__.py\", line 1883, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\nelso\\Documents\\G_Drive\\Master\\BHT_ICE\\MasterKoloquium\\B\\EMNIST\\user_interface.py\", line 47, in __draw\n",
      "    cls.__draw_Obj.ellipse([(event.x-offs),(event.y-offs), event.x+offs, event.y+offs], fill='white')\n",
      "AttributeError: 'function' object has no attribute 'ellipse'\n"
     ]
    }
   ],
   "source": [
    "Gui.start(let_MLP_clf)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'ui' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-13-ac8b6948e926>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[1;32m----> 1\u001b[1;33m \u001b[0mui\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mGui\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mlet_MLP_clf\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[1;31mNameError\u001b[0m: name 'ui' is not defined"
     ]
    }
   ],
   "source": [
    "ui.Gui(let_MLP_clf)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
